version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php8-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  nginx:
    image: nginx:1.20-alpine
    container_name: php8-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d